name: Build & Push branches
on:
  push:
    branches:
      - 'develop'
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push develop
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/develop'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            softizy/varnish-with-prom-exporter-docker:develop
            ghcr.io/softizy/varnish-with-prom-exporter-docker:develop
      -
        name: Build and push latest
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            softizy/varnish-with-prom-exporter-docker:latest
            ghcr.io/softizy/varnish-with-prom-exporter-docker:latest
