name: Push README to Docker Hub
on:
  push:
    branches:
      - 'main'
jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: softizy/varnish-with-prom-exporter-docker
          provider: dockerhub
          short_description: 'Varnish docker container with prometheus_varnish_exporter baked in'
          readme_file: 'README.md'
