name: Build & Push branches
on:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
      - '*'
  pull_request:
    branches:
      - 'develop'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            softizy/varnish-with-prom-exporter-docker
            ghcr.io/softizy/varnish-with-prom-exporter-docker
      -
        name: Show tags
        run: echo '::notice title=TAGS::${{ steps.meta.outputs.tags }}'
      -
        name: Show labels
        run: echo '::notice title=LABELS::${{ steps.meta.outputs.labels }}'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/develop'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
